# general parameters, all systems and problems
reference: "idbastar_v0_freetime"
default:
  solver_id: 9
  smooth_traj: true
  linear_search: true

acrobot_v0:
  default:
    max_iter: 200
    weight_goal: 300

quad3d_v0:
  default:
    max_iter: 200
    weight_goal: 200
    smooth_traj: true
