# general parameters, all systems and problems
reference: "idbastar_v0_freetime"
default:
  solver_id: 9
  smooth_traj: true
  search_timelimit: 15000 # in ms

car1_v0:
  default:
    use_nigh_nn: true
    motionsFile: "../cloud/motionsV2/good/car1_v0/car1_v0_all.bin.sp.bin"
    num_primitives_0: 2000
    max_motions_primitives: 20000

quad2d_v0:
  default:
    # motionsFile: "../cloud/motionsV2/good/quad2d_v0/quad2_all_split_2_sorted.bin"
    motionsFile: "../cloud/motionsV2/good/quad2d_v0/quad2d_v0_all.bin.sp1.bin"
    # num_primitives_0: 50000
    # max_motions_primitives: 100000
    num_primitives_0: 5000
    max_motions_primitives: 50000
    delta_0: .7
    use_nigh_nn: true
    linear_search: true

acrobot_v0:
  default:
    delta_factor_goal: .7
    linear_search: true
    use_nigh_nn: true # library for knn
    # motionsFile: "../cloud/motionsV2/good/acrobot_v0/acrobot_v0_all.bin.sp.bin.so.bin"
    motionsFile: "../cloud/motionsV2/good/acrobot_v0/acrobot_v0_all2.bin.sp.bin"
    num_primitives_0: 100000
    max_motions_primitives: 200000
    check_cols: false
    delta_0: .35
    max_iter: 200
    weight_goal: 300

quad3d_v0:
  default:
    max_iter: 200
    weight_goal: 200
    smooth_traj: true
    linear_search: true
