trials: 1
timelimit: 60
n_cores: -1 # -1=auto

problems:
  - unicycle1_v0/bugtrap_0
  - unicycle2_v0/bugtrap_0
  - quad2d_v0/quad_bugtrap
algs:
  - idbastar_v0_analysis_d1
  - idbastar_v0_analysis_d2
