files:
- ../results_new_timeopt/unicycle_first_order_0/bugtrap_0/delta_02_v0/idbastar_v0_fixedtime/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/unicycle_first_order_0/bugtrap_0/delta_02_v0/idbastar_v0_freetime/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/unicycle_first_order_0/bugtrap_0/delta_02_v0/idbastar_v0_mpc/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/unicycle_first_order_0/bugtrap_0/delta_02_v0/idbastar_v0_mpcc/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/unicycle_first_order_0/bugtrap_0/delta_02_v0/idbastar_v0_search/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/unicycle_first_order_0/bugtrap_0/delta_05_v0/idbastar_v0_fixedtime/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/unicycle_first_order_0/bugtrap_0/delta_05_v0/idbastar_v0_freetime/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/unicycle_first_order_0/bugtrap_0/delta_05_v0/idbastar_v0_mpc/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/unicycle_first_order_0/bugtrap_0/delta_05_v0/idbastar_v0_mpcc/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/unicycle_first_order_0/bugtrap_0/delta_05_v0/idbastar_v0_search/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/unicycle_second_order_0/bugtrap_0/delta_02_v0/idbastar_v0_fixedtime/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/unicycle_second_order_0/bugtrap_0/delta_02_v0/idbastar_v0_freetime/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/unicycle_second_order_0/bugtrap_0/delta_02_v0/idbastar_v0_mpc/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/unicycle_second_order_0/bugtrap_0/delta_02_v0/idbastar_v0_mpcc/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/unicycle_second_order_0/bugtrap_0/delta_02_v0/idbastar_v0_search/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/unicycle_second_order_0/bugtrap_0/delta_05_v0/idbastar_v0_fixedtime/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/unicycle_second_order_0/bugtrap_0/delta_05_v0/idbastar_v0_freetime/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/unicycle_second_order_0/bugtrap_0/delta_05_v0/idbastar_v0_mpc/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/unicycle_second_order_0/bugtrap_0/delta_05_v0/idbastar_v0_mpcc/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/unicycle_second_order_0/bugtrap_0/delta_05_v0/idbastar_v0_search/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/quad2d/quad_bugtrap/delta_05_v0/idbastar_v0_fixedtime/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/quad2d/quad_bugtrap/delta_05_v0/idbastar_v0_freetime/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/quad2d/quad_bugtrap/delta_05_v0/idbastar_v0_mpc/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/quad2d/quad_bugtrap/delta_05_v0/idbastar_v0_mpcc/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/quad2d/quad_bugtrap/delta_05_v0/idbastar_v0_search/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/quad2d/quad_bugtrap/delta_045_v0/idbastar_v0_fixedtime/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/quad2d/quad_bugtrap/delta_045_v0/idbastar_v0_freetime/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/quad2d/quad_bugtrap/delta_045_v0/idbastar_v0_mpc/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/quad2d/quad_bugtrap/delta_045_v0/idbastar_v0_mpcc/2023-07-06--21-54-28/report.yaml
- ../results_new_timeopt/quad2d/quad_bugtrap/delta_045_v0/idbastar_v0_search/2023-07-06--21-54-28/report.yaml
output: ../results_new_timeopt/plots/plot_time_2023-07-06--21-54-56.pdf
