files:
- ../results_new_search/unicycle_first_order_0/bugtrap_0/dbastar_v0_heu0/2023-07-06--19-11-30/report.yaml
- ../results_new_search/unicycle_first_order_0/bugtrap_0/dbastar_v0_heu1/2023-07-06--19-11-30/report.yaml
- ../results_new_search/unicycle_first_order_0/bugtrap_0/dbastar_v0_heuNO/2023-07-06--19-11-30/report.yaml
- ../results_new_search/unicycle_second_order_0/bugtrap_0/dbastar_v0_heu0/2023-07-06--19-11-30/report.yaml
- ../results_new_search/unicycle_second_order_0/bugtrap_0/dbastar_v0_heu1/2023-07-06--19-11-30/report.yaml
- ../results_new_search/unicycle_second_order_0/bugtrap_0/dbastar_v0_heuNO/2023-07-06--19-11-30/report.yaml
- ../results_new_search/quad2d/quad_bugtrap/dbastar_v0_heu0/2023-07-06--19-11-30/report.yaml
- ../results_new_search/quad2d/quad_bugtrap/dbastar_v0_heu1/2023-07-06--19-11-30/report.yaml
- ../results_new_search/quad2d/quad_bugtrap/dbastar_v0_heuNO/2023-07-06--19-11-30/report.yaml
- ../results_new_search/car_first_order_with_1_trailers_0/bugtrap_0/dbastar_v0_heu0/2023-07-06--19-11-30/report.yaml
- ../results_new_search/car_first_order_with_1_trailers_0/bugtrap_0/dbastar_v0_heu1/2023-07-06--19-11-30/report.yaml
- ../results_new_search/car_first_order_with_1_trailers_0/bugtrap_0/dbastar_v0_heuNO/2023-07-06--19-11-30/report.yaml
- ../results_new_search/quadrotor_0/quad_one_obs/dbastar_v0_heu0/2023-07-06--19-11-30/report.yaml
- ../results_new_search/quadrotor_0/quad_one_obs/dbastar_v0_heu1/2023-07-06--19-11-30/report.yaml
- ../results_new_search/quadrotor_0/quad_one_obs/dbastar_v0_heuNO/2023-07-06--19-11-30/report.yaml
- ../results_new_search/quadrotor_0/window/dbastar_v0_heu0/2023-07-06--19-11-30/report.yaml
- ../results_new_search/quadrotor_0/window/dbastar_v0_heu1/2023-07-06--19-11-30/report.yaml
- ../results_new_search/quadrotor_0/window/dbastar_v0_heuNO/2023-07-06--19-11-30/report.yaml
- ../results_new_search/quad2dpole/window/dbastar_v0_heu0/2023-07-06--19-11-30/report.yaml
- ../results_new_search/quad2dpole/window/dbastar_v0_heu1/2023-07-06--19-11-30/report.yaml
- ../results_new_search/quad2dpole/window/dbastar_v0_heuNO/2023-07-06--19-11-30/report.yaml
